
analysis_name: mruby # defaults to analysis

## working directory defaults to current working directory
## all relative paths specified herein are assumed to be in the working_dir
## any files not in working_dir should be specified with an absolute path
#working_dir:

multiprocessing: all # "all", or "half", or -1 means all but one, defaults to -1

material:
  definitions: materials_v0p6.hexrd
  active: ruby

## !!! currently ignores this block in v0.6
image_series:
  file:
    stem: null
    ids: [] # or can use globs: ["*2[4-9]"]
  images:
    start: 0 # 0-based
  omega:
    start: 0.
    stop: 0.
    step: 0.
  dark: null
  flip: null

instrument:
  parameters: ./dexelas_id3a_20200130.yml
  ## currently igonres the rest of this block
  detector: # this section is only needed to convert old files to the new spec
    parameters_old: null
    pixels: # this section required to convert from old detector spec
      rows: null
      columns: null
      size: null

find_orientations:
  orientation_maps:
    # A file name must be specified. If it doesn't exist, one will be created
    file: null

    threshold: 0
    bin_frames: 1 # defaults to 1

    ## "all", or a list of hkl orders used to find orientations
    ## defaults to all orders listed in the material definition
    active_hkls: [0,1,2,3,4,5]

  ## either search full quaternion grid, or seed search based on sparse
  ## orientation maps
  #use_quaternion_grid: some/file/name # defaults to seeded search
  seed_search: # this section is ignored if use_quaternion_grid is defined
    hkl_seeds: [0,1,2] # hkls ids to use, must be defined for seeded search
    fiber_step: 0.5 # degrees, defaults to ome tolerance

  threshold: 250 # defaults to 1

  omega:
    tolerance: 1.0 # in degrees, defaults to 2x ome step

    ## specify the branch cut, in degrees. The range must be 360 degrees.
    period: [0, 360] # in degrees, defaults to full 360 starting at "ome start"

  eta:
    tolerance: 1.0 # in degrees, defaults to 2x ome step
    mask: 5 # degrees, mask angles close to ome rotation axis, defaults to 5

  clustering:
    radius: 1.0
    completeness: 0.85 # completeness threshold
    #algorithm: fclusterdata # defaults to dbscan

fit_grains:
  do_fit: true # if false, extracts grains but doesn't fit. defaults to true

  #estimate: null

  npdiv: 4 # number of polar pixel grid subdivisions, defaults to 2

  panel_buffer: 2 # don't fit spots within this many mm from edge

  threshold: 25

  tolerance:
    tth: [0.25, 0.20] # tolerance lists must be identical length
    eta: [3.0, 2.0]
    omega: [2.0, 1.0]

  refit: [1, 1]

  tth_max: false # true, false, or a non-negative value, defaults to true

